name: llmrobot
channels:
  - conda-forge
dependencies:
  - pytest-asyncio
  - pydantic
  - httpx
  - python-dotenv
  - pydantic-ai
  - jupyterlab
  - pip
  - mcp
  - matplotlib
  - python=3.12
  - pandas
  - pytest
  - ruff
  - fastmcp
  - google-genai
